CREATE TABLE locator_country (
  locator_country_id int(10) NOT NULL auto_increment,
  locator_country_code varchar(2) default NULL,
  locator_country_descr varchar(255) default NULL,
  locator_country_status varchar(10) default '1',
  PRIMARY KEY  (locator_country_id),
  KEY locator_country_desc (locator_country_descr),
  KEY locator_country_code (locator_country_code)
) ENGINE=MyISAM;
CREATE TABLE locator_cat (
  locator_cat_id int(10) NOT NULL auto_increment,
  locator_catname varchar(255) default NULL,
  locator_image_path varchar(255) default NULL,
  locator_test_01 varchar(30) default NULL,
  locator_test_02 varchar(30) default NULL,
  locator_test_03 varchar(30) default NULL,
  locator_test_04 varchar(30) default NULL,
  locator_test_integer int(10) NOT NULL default '0',
  locator_catactive_status varchar(10) default NULL,
  locator_catorder int(11) NOT NULL default '1',
  locator_cat_class int(11) NOT NULL,
  PRIMARY KEY  (locator_cat_id)
) ENGINE=MyISAM;
CREATE TABLE locator_sites (
  locator_id int(10) NOT NULL auto_increment,
  locator_client varchar(255) default NULL,
  locator_address1 varchar(255) default NULL,
  locator_address2 varchar(255) default NULL,
  locator_address3 varchar(255) default NULL,
  locator_zipcode varchar(255) default NULL,
  locator_city varchar(255) default NULL,
  locator_county varchar(255) default NULL,
  locator_state varchar(255) default NULL,
  locator_country varchar(255) default NULL,
  locator_sitename varchar(255) default NULL,
  locator_manager1 varchar(255) default NULL,
  locator_manager2 varchar(255) default NULL,
  locator_telephone1 varchar(255) default NULL,
  locator_telephone2 varchar(255) default NULL,
  locator_fax1 varchar(255) default NULL,
  locator_fax2 varchar(255) default NULL,
  locator_email1 varchar(255) default NULL,
  locator_email2 varchar(255) default NULL,
  locator_latitude varchar(255) default NULL,
  locator_longtitude varchar(255) default NULL,
  locator_groundelevation varchar(255) default NULL,
  locator_verified varchar(255) default NULL,
  locator_cat varchar(255) default NULL,
  locator_status varchar(255) default NULL,
  locator_description1 varchar(255) default NULL,
  locator_description2 varchar(255) default NULL,
  locator_url1 varchar(255) default NULL,
  locator_url2 varchar(255) default NULL,
  locator_catid int(10) default NULL,
  locator_order varchar(255) default NULL,
  locator_active_status varchar(255) default NULL,
  locator_open_mo varchar(255) default NULL,
  locator_open_tu varchar(255) default NULL,
  locator_open_we varchar(255) default NULL,
  locator_open_th varchar(255) default NULL,
  locator_open_fr varchar(255) default NULL,
  locator_open_sa varchar(255) default NULL,
  locator_open_su varchar(255) default NULL,
  locator_open_remarks varchar(255) default NULL,
  PRIMARY KEY  (locator_id),
  KEY locator_zipcode (locator_zipcode),
  KEY locator_client (locator_client),
  KEY locator_order (locator_order)
) ENGINE=MyISAM;
CREATE TABLE locator_sub_sites (
  locator_sub_id int(10) NOT NULL auto_increment,
  locator_sub_client varchar(255) default NULL,
  locator_sub_address1 varchar(255) default NULL,
  locator_sub_address2 varchar(255) default NULL,
  locator_sub_address3 varchar(255) default NULL,
  locator_sub_zipcode varchar(255) default NULL,
  locator_sub_city varchar(255) default NULL,
  locator_sub_county varchar(255) default NULL,
  locator_sub_state varchar(255) default NULL,
  locator_sub_country varchar(255) default NULL,
  locator_sub_sitename varchar(255) default NULL,
  locator_sub_manager1 varchar(255) default NULL,
  locator_sub_manager2 varchar(255) default NULL,
  locator_sub_telephone1 varchar(255) default NULL,
  locator_sub_telephone2 varchar(255) default NULL,
  locator_sub_fax1 varchar(255) default NULL,
  locator_sub_fax2 varchar(255) default NULL,
  locator_sub_email1 varchar(255) default NULL,
  locator_sub_email2 varchar(255) default NULL,
  locator_sub_latitude varchar(255) default NULL,
  locator_sub_longtitude varchar(255) default NULL,
  locator_sub_groundelevation varchar(255) default NULL,
  locator_sub_verified varchar(255) default NULL,
  locator_sub_cat varchar(255) default NULL,
  locator_sub_status varchar(255) default NULL,
  locator_sub_description1 varchar(255) default NULL,
  locator_sub_description2 varchar(255) default NULL,
  locator_sub_url1 varchar(255) default NULL,
  locator_sub_url2 varchar(255) default NULL,
  locator_sub_catid int(10) default NULL,
  locator_sub_order varchar(255) default NULL,
  locator_sub_active_status varchar(255) default NULL,
  locator_sub_open_mo varchar(255) default NULL,
  locator_sub_open_tu varchar(255) default NULL,
  locator_sub_open_we varchar(255) default NULL,
  locator_sub_open_th varchar(255) default NULL,
  locator_sub_open_fr varchar(255) default NULL,
  locator_sub_open_sa varchar(255) default NULL,
  locator_sub_open_su varchar(255) default NULL,
  locator_sub_open_remarks varchar(255) default NULL,
  locator_sub_datestamp int(10) NOT NULL default '0',
  locator_sub_ip varchar(15) NOT NULL default '',
  locator_sub_auth tinyint(3) NOT NULL default '0',
  locator_sub_name varchar(100) default NULL,
  locator_sub_email varchar(100) default NULL,
  PRIMARY KEY  (locator_sub_id)
) ENGINE=MyISAM;