<?php
/*
+------------------------------------------------------------------------------+
|   EasyGallery - a plugin by nlstart
|
|	Plugin Support Site: e107.webstartinternet.com
|
|	For the e107 website system visit http://e107.org
|
|	Released under the terms and conditions of the
|	GNU General Public License (http://gnu.org).
+------------------------------------------------------------------------------+
*/
// module plugin.php
define("EG_NAME", "EasyGallery");
define("EG_DESC", "A simple gallery with autogenerated thumbnails.");
define("EG_MENU", "EasyGallery");
define("EG_LINK_NAME", "EasyGallery"); // To demonstrate your link name can be different than plugin name
define("EG_CAPTION", "Configure EasyGallery");
define("EG_DONE1", "Installation ");
define("EG_DONE2", "successful...");
define("EG_DONE3", "Thank you for upgrading to"); // Plugin version will be added automatically
define("EG_CHMOD", "Subfolder easygallery/gallery needs to be set to CHMOD 777 manually.");
define("EG_LATEST", "Uploaded images");

// module admin_menu.php
define("EG_MENU_00", "EasyGallery Options");
define("EG_MENU_01", "EasyGallery Settings");
define("EG_MENU_02", "Manage images folder");
define("EG_MENU_03", "*");
define("EG_MENU_04", "*");
define("EG_MENU_05", "*");
define("EG_MENU_06", "*");
define("EG_MENU_07", "*");
define("EG_MENU_08", "*");
define("EG_MENU_09", "Readme");
define("EG_MENU_10", "Support this plugin");
define("EG_MENU_11", "Please make an online donation today here");

// module admin_config.php
define("EG_CONF_00", "EasyGallery Configuration");
define("EG_CONF_01", "Maintain EasyGallery Settings");
define("EG_CONF_02", "Maximum thumbnail image width/height");
define("EG_CONF_03", "Make thumbnails universal height/width?");
define("EG_CONF_04", "(gd2 only)");
define("EG_CONF_05", "Yes");
define("EG_CONF_06", "No");
define("EG_CONF_07", "Border color (RGB) when using universal height");
define("EG_CONF_08", "E.g. 255,255,255 = White or 0,0,0 = Black");
define("EG_CONF_09", "Use subdirectories of the Gallery folder as separate albums?");
define("EG_CONF_10", "Apply Changes");
define("EG_CONF_11", "Your settings have been saved.");
define("EG_CONF_12", "Thumbnail jpeg image quality (0-100)");
define("EG_CONF_13", "Show file names under the image? (e.g.: image1.jpg)");
define("EG_CONF_14", "Display images within EasyGallery?");
define("EG_CONF_15", "Setting 'No' will open images in a new window (without html)");
define("EG_CONF_16", "Default sort order");
define("EG_CONF_17", "Name ascending");
define("EG_CONF_18", "Name descending");
define("EG_CONF_19", "Old to new");
define("EG_CONF_20", "New to old");
define("EG_CONF_21", "Delete redundant thumbnails?");
define("EG_CONF_22", "No, never");
define("EG_CONF_23", "Yes, check monthly");
define("EG_CONF_24", "Yes, check every time");
define("EG_CONF_25", "Method to create thumbnails");
define("EG_CONF_26", "gd2");
define("EG_CONF_27", "imagemagick");
define("EG_CONF_28", "Override path to Imagemagick 'convert' program");
define("EG_CONF_29", "If left empty, e107 core imagepath will be used. Expected default: '/usr/bin/convert'.");
define("EG_CONF_30", "Override path to Imagemagick 'identify' program");
define("EG_CONF_31", "If left empty, e107 core imagepath will be used. Expected default: '/usr/bin/identify'");
define("EG_CONF_32", "Gallery images folder");
define("EG_CONF_33", "Enable comments");
define("EG_CONF_34", "Uploads allowed for class");
define("EG_CONF_35", "Maximum number of images to upload at once");
define("EG_CONF_36", "Current e107 Imagemagick path (Admin > Images)");
define("EG_CONF_37", "Maximum size full images");
define("EG_CONF_38", "pixels");
define("EG_CONF_39", "Thumbnail image size cannot be blank or zero (default suggested value is 150).");
define("EG_CONF_40", "Full image size cannot be blank or zero (default suggested value is 600).");

// module gallery.php
define("EG_CORE_00", "Gallery");
define("EG_CORE_01", "Template file for gallery: [TEMPLATE_FILE] does not exist. Check your EasyGallery settings; the value of setting 'Gallery images folder' is probably incorrect."); // Do not translate [TEMPLATE_FILE]
define("EG_CORE_02", "Error");
define("EG_CORE_03", "Use the [BACK_BUTTON] of your browser to try again."); // Do not translate [BACK_BUTTON]
define("EG_CORE_04", "back button"); 
define("EG_CORE_05", "Directory [CONFIG_DIR] does not exist."); // Do not translate [CONFIG_DIR]
define("EG_CORE_06", "Could not create thumb directory [CONFIG_THUMBS] - check write permissions."); // Do not translate [CONFIG_THUMBS]
define("EG_CORE_07", "No images available");
define("EG_CORE_08", "Name ascending");
define("EG_CORE_09", "Name descending");
define("EG_CORE_10", "New to old");
define("EG_CORE_11", "Old to new");
define("EG_CORE_12", "Album");
define("EG_CORE_13", "Images shown");
define("EG_CORE_14", "of");
define("EG_CORE_15", "Images per page");
define("EG_CORE_16", "Sorted on");
define("EG_CORE_17", "Total number of pages");
define("EG_CORE_18", "Gallery start page");
define("EG_CORE_19", "Edit description");
define("EG_CORE_20", "Save changes");
define("EG_CORE_21", "Sorry, the requested image apparently does not exist any more.");
define("EG_CORE_22", "Image description");
define("EG_CORE_23", "Last modified");
define("EG_CORE_24", "Previous");
define("EG_CORE_25", "Next");
define("EG_CORE_26", "Back");
define("EG_CORE_27", "You do not appear to have phpthumbs.bmp.php installed in the same path as gallery.php. Please add this file, or remove .bmp files from your image directory");
define("EG_CORE_28", "Upload images");
define("EG_CORE_29", "Image");
define("EG_CORE_30", "uploaded");
define("EG_CORE_31", "Uploaded by");
define("EG_CORE_32", "The file you request is not an image!");
define("EG_CORE_33", "NOT uploaded because the file name has no valid image extension!");
define("EG_CORE_34", "Your uploaded files need to be approved by an administrator before being displayed.");

// module admin_overview.php
define("EG_UPLOAD_10", "Error");
define("EG_UPLOAD_12", "file");
define("EG_UPLOAD_13", "files");
define("EG_UPLOAD_14", "directory");
define("EG_UPLOAD_15", "directories");
define("EG_UPLOAD_16", "Root directory");
define("EG_UPLOAD_17", "Name");
define("EG_UPLOAD_18", "Size");
define("EG_UPLOAD_19", "Last Modified");
define("EG_UPLOAD_21", "Upload file to this dir");
define("EG_UPLOAD_22", "Upload");
define("EG_UPLOAD_26", "Deleted");
define("EG_UPLOAD_27", "successfully");
define("EG_UPLOAD_28", "Unable to delete");
define("EG_UPLOAD_29", "Path");
define("EG_UPLOAD_30", "Up level");
define("EG_UPLOAD_31", "folder");
define("EG_UPLOAD_32", "Select Directory");
define("EG_UPLOAD_33", "Select");
define("EG_UPLOAD_34", "Directory choice");
define("EG_UPLOAD_38", "Successfully moved file to");
define("EG_UPLOAD_39", "Unable to move file to");
define("EG_UPLOAD_43", "Delete selected files");
define("EG_UPLOAD_46", "Please confirm that you wish to DELETE the selected files.");
define("EG_UPLOAD_47", "User Uploads");
define("EG_UPLOAD_48", "Move selected to");
define("EG_UPLOAD_49", "Please confirm you wish to move the selected files.");
define("EG_UPLOAD_50", "Move");
define("EG_UPLOAD_51", "Add gallery directory");
define("EG_UPLOAD_52", "New gallery directory");
define("EG_UPLOAD_53", "Succesfully created directory");
define("EG_UPLOAD_54", "Failed to create directory");
define("EG_UPLOAD_55", "User");
define("EG_UPLOAD_56", "Upload failed (probably duplicate file name)");

// module help.php
define("EG_ADMIN_HELP_00", "EasyGallery Help");
define("EG_ADMIN_HELP_01", "EasyGallery Settings");
define("EG_ADMIN_HELP_02", "Manage your EasyGallery preferences.");
define("EG_ADMIN_HELP_03", "Manage images folder");
define("EG_ADMIN_HELP_04", "Manage your images (sub-)folder(s); view, add and delete images.");
define("EG_ADMIN_HELP_05", "");
define("EG_ADMIN_HELP_06", "");
define("EG_ADMIN_HELP_07", "ReadMe.txt");  // Also used in admin_readme.php
define("EG_ADMIN_HELP_08", "View the Readme text file for detailed release information and version history.<br/><br/>For additional help on this plugin view the <a target='_blank' href='http://wiki.e107.org/?title=EasyGallery'>e107 Wiki pages</a>.");
define("EG_ADMIN_HELP_99", "readme.txt"); // Actual helpfile called by admin_readme.php to allow for multi-langual helpfiles
?>