<?php

	$form_text = "<form method='POST' action='index.php?SendMail'>\n"
				."<input name='frmaction' type='hidden' value='SendMail'>\n"
				."<input type='hidden' name='link_subject' value='".LINKREQUEST_00."'>\n"
				."<table class='tborder'>"
                        ."<tr>\n"
					."<td class='tborder' valign='top' align='right'>".LINKREQUEST_01."</td>\n"
                              ."<td class='tborder' align='left'>"
                              ."<input class='tbox' name='link_name' type='text' value='' maxlength='50' size='50'>"
					."</td>\n"
				."</tr>\n"
				."<tr>\n"
					."<td class='tborder' valign='top' align='right'>".LINKREQUEST_02."</td>\n"
					."<td class='tborder' align='left'>"
					."<input class='tbox' name='link_email' type='text' value='' maxlength='50' size='50'>"
					."</td>\n"
				."</tr>\n"
				."<tr>\n"
					."<td class='tborder' valign='top' align='right'>".LINKREQUEST_03."</td>\n"
					."<td class='tborder' align='left'>"
					."<input class='tbox' name='link_website' type='text' value='' maxlength='50' size='50'>"
					."</td>\n"
				."</tr>\n"
				."<tr>\n"
					."<td class='tborder' valign='top' align='right'>".LINKREQUEST_04."</td>\n"
					."<td class='tborder' align='left'>"
					."<textarea class='tbox' name='link_message' wrap='soft' rows='5' cols='37'></textarea>"
					."</td>\n"
				."</tr>\n"
				."<tr>\n"
					."<td colspan='2' class='spacer' style='text-align:center;'>"
					."<input class='button' name='submit' type='submit' value='".LINKREQUEST_05."'>"
					."<input class='button' name='reset' type='reset' value='".LINKREQUEST_06."'>"
					."</td>"
				."</tr>\n"
                        ."</table>"
?>
