CREATE TABLE pd_categories (
  pd_cat_id int(10) unsigned NOT NULL auto_increment,
  pd_cat_desc varchar(30) default NULL,
  pd_cat_viewclass int(10) unsigned NOT NULL default '0',
  pd_cat_updated int(10) unsigned NOT NULL default '0',
  pd_cat_order int(10) unsigned NOT NULL default '0',
  pd_cat_updateby varchar(100) default NULL,
  PRIMARY KEY  (pd_cat_id)
  ) TYPE=MyISAM;
CREATE TABLE pd_department (
  pd_dept_id int(10) unsigned NOT NULL auto_increment,
  pd_dept_name varchar(40) default NULL,
  pd_dept_mgr varchar(20) default NULL,
  pd_dept_phone varchar(20) default NULL,
  pd_dept_fax varchar(20) default NULL,
  pd_dept_comment varchar(200) default NULL,
  pd_dept_email varchar(100) default NULL,
  pd_dept_phonecentrex varchar(20) default NULL,
  pd_dept_faxcentrex varchar(20) default NULL,
  pd_dept_updated int(10) unsigned NOT NULL default '0',
  pd_dept_updateby varchar(100) default NULL,
  PRIMARY KEY  (pd_dept_id)
) TYPE=MyISAM;
CREATE TABLE pd_directory (
  pd_id int(10) NOT NULL auto_increment,
  pd_last_name varchar(40) default NULL,
  pd_first_name varchar(40) default NULL,
  pd_work_phone varchar(20) default NULL,
  pd_fax varchar(20) default NULL,
  pd_mobile varchar(20) default NULL,
  pd_department int(10) unsigned NOT NULL default '0',
  pd_site int(10) unsigned NOT NULL default '0',
  pd_email varchar(160) default NULL,
  pd_comments text,
  pd_centrex varchar(10) default NULL,
  pd_dir_cat int(10) unsigned NOT NULL default '0',
  pd_officed tinyint(1) unsigned NOT NULL default '1',
  pd_jobtitle int(10) unsigned NOT NULL default '0',
  pd_updated int(10) unsigned NOT NULL default '0',
  pd_updatedby varchar(100) default NULL,
  pd_picture varchar(200) default NULL,
    pd_address1 varchar(50) default NULL,
  pd_address2 varchar(50) default NULL,
  pd_town varchar(50) default NULL,
  pd_county varchar(50) default NULL,
  pd_postcode varchar(20) default NULL,
  pd_country varchar(50) default NULL,
  PRIMARY KEY  (pd_id)
) TYPE=MyISAM;
CREATE TABLE pd_jobtitle (
  pd_job_id int(10) unsigned NOT NULL auto_increment,
  pd_job_title varchar(40) default NULL,
  pd_job_updated int(10) unsigned NOT NULL default '0',
  pd_job_updatedby varchar(100) default NULL,
  PRIMARY KEY  (pd_job_id),
) TYPE=MyISAM;
CREATE TABLE pd_sites (
  pd_site_id int(10) unsigned NOT NULL auto_increment,
  pd_site_name varchar(25) default NULL,
  pd_site_address1 varchar(30) default NULL,
  pd_site_address2 varchar(30) default NULL,
  pd_site_town varchar(25) default NULL,
  pd_site_postcode varchar(10) default NULL,
  pd_site_phone varchar(15) default NULL,
  pd_site_fax varchar(15) default NULL,
  pd_site_comment varchar(200) default NULL,
  pd_site_faxcentrex varchar(10) default NULL,
  pd_site_phonecentrex varchar(10) default NULL,
  pd_site_county varchar(15) default NULL,
  pd_site_mapurl varchar(250) default NULL,
  pd_site_updated int(10) unsigned NOT NULL default '0',
  pd_site_updatedby varchar(100) default NULL,
  PRIMARY KEY  (pd_site_id),
) TYPE=MyISAM;