CREATE TABLE cpage_page (
  cpage_id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  cpage_title VARCHAR(250) NOT NULL DEFAULT '',
  cpage_text MEDIUMTEXT NOT NULL,
  cpage_author VARCHAR(100) NOT NULL DEFAULT '',
  cpage_datestamp INT(11) UNSIGNED NOT NULL DEFAULT '0',
  cpage_showdate_flag TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  cpage_lastdate_flag TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  cpage_showauthor_flag TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  cpage_rating_flag TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  cpage_comment_flag TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  cpage_page_flag TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  cpage_menu_flag TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  cpage_email_flag TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  cpage_print_flag TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  cpage_pdf_flag TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  cpage_views_flag TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  cpage_unique_flag TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  cpage_password VARCHAR(50) NOT NULL DEFAULT '',
  cpage_class INT(11) UNSIGNED NOT NULL DEFAULT '0',
  cpage_ip_restrict TEXT NOT NULL,
  cpage_meta_description VARCHAR(250) NOT NULL DEFAULT '',
  cpage_meta_keywords VARCHAR(250) NOT NULL DEFAULT '',
  cpage_meta_title VARCHAR(50) NOT NULL DEFAULT '',
  cpage_views INT(11) UNSIGNED NOT NULL DEFAULT '0',
  cpage_unique INT(11) UNSIGNED NOT NULL DEFAULT '0',
  cpage_lastupdate INT(11) UNSIGNED NOT NULL DEFAULT '0',
  cpage_revision INT(11) UNSIGNED NOT NULL DEFAULT '0',
  cpage_link VARCHAR(100) NOT NULL DEFAULT '',
  cpage_canonical VARCHAR(100) NOT NULL DEFAULT '',
  cpage_showfrom INT(11) UNSIGNED NOT NULL DEFAULT '0',
  cpage_showto INT(11) UNSIGNED NOT NULL DEFAULT '0',
  cpage_category INT(11) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY  (cpage_id),
  KEY  cpage_id (cpage_id),
  KEY cpage_title (cpage_title),
  KEY cpage_category (cpage_category),
  FULLTEXT KEY cpage_text (cpage_text)
) TYPE=MYISAM;
CREATE TABLE cpage_revisions (
  cpage_r_revision_id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  cpage_r_id INT(11) UNSIGNED NOT NULL DEFAULT '0',
  cpage_r_title VARCHAR(250) NOT NULL DEFAULT '',
  cpage_r_text MEDIUMTEXT NOT NULL,
  cpage_r_author VARCHAR(100) NOT NULL DEFAULT '',
  cpage_r_datestamp INT(11) UNSIGNED NOT NULL DEFAULT '0',
  cpage_r_showdate_flag TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  cpage_r_lastdate_flag TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  cpage_r_showauthor_flag TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  cpage_r_rating_flag TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  cpage_r_comment_flag TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  cpage_r_page_flag TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  cpage_r_menu_flag TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  cpage_r_email_flag TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  cpage_r_print_flag TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  cpage_r_pdf_flag TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  cpage_r_views_flag TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  cpage_r_unique_flag TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  cpage_r_password VARCHAR(50) NOT NULL DEFAULT '',
  cpage_r_class INT(11) UNSIGNED NOT NULL DEFAULT '0',
  cpage_r_ip_restrict TEXT NOT NULL,
  cpage_r_meta_description VARCHAR(250) NOT NULL DEFAULT '',
  cpage_r_meta_keywords VARCHAR(250) NOT NULL DEFAULT '',
  cpage_r_meta_title VARCHAR(50) NOT NULL DEFAULT '',
  cpage_r_views INT(11) UNSIGNED NOT NULL DEFAULT '0',
  cpage_r_unique INT(11) UNSIGNED NOT NULL DEFAULT '0',
  cpage_r_lastupdate INT(11) UNSIGNED NOT NULL DEFAULT '0',
  cpage_r_revision INT(11) UNSIGNED NOT NULL DEFAULT '0',
  cpage_r_revisor VARCHAR(100) NOT NULL DEFAULT '',
  cpage_r_link VARCHAR(100) NOT NULL DEFAULT '',
  cpage_r_canonical VARCHAR(100) NOT NULL DEFAULT '',
  cpage_r_showfrom INT(11) UNSIGNED NOT NULL DEFAULT '0',
  cpage_r_showto INT(11) UNSIGNED NOT NULL DEFAULT '0',
  cpage_r_category INT(11) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY  (cpage_r_revision_id),
  KEY cpage_r_id (cpage_r_id),
  KEY cpage_r_revision (cpage_r_revision)
) TYPE=MYISAM;
CREATE TABLE cpage_view_history (
  cpage_hist_page VARCHAR(30) NOT NULL DEFAULT '',
  PRIMARY KEY  (cpage_hist_page)
) TYPE=MYISAM;
CREATE TABLE cpage_category (
  cpage_cat_id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  cpage_cat_name VARCHAR(30) NOT NULL DEFAULT '',
  cpage_cat_order INT(11) UNSIGNED NOT NULL DEFAULT '0',
  cpage_cat_parent INT(11) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY  (cpage_cat_id)
) TYPE=MYISAM;