CREATE TABLE reviewer_category (
  reviewer_category_id int(10) unsigned NOT NULL auto_increment,
  reviewer_category_name VARCHAR(50) default NULL,
  reviewer_category_description TEXT,
  reviewer_category_updated int(10) unsigned NOT NULL default '0',
  reviewer_category_icon VARCHAR(50) default NULL,
  reviewer_category_use1 tinyint(3) unsigned NOT NULL default '0',
  reviewer_category_use2 tinyint(3) unsigned NOT NULL default '0',
  reviewer_category_use3 tinyint(3) unsigned NOT NULL default '0',
  reviewer_category_use4 tinyint(3) unsigned NOT NULL default '0',
  reviewer_category_use5 tinyint(3) unsigned NOT NULL default '0',
  reviewer_category_use6 tinyint(3) unsigned NOT NULL default '0',
  reviewer_category_use7 tinyint(3) unsigned NOT NULL default '0',
  reviewer_category_use8 tinyint(3) unsigned NOT NULL default '0',
  reviewer_category_use9 tinyint(3) unsigned NOT NULL default '0',
  reviewer_category_use10 tinyint(3) unsigned NOT NULL default '0',
  reviewer_category_rate1 VARCHAR(20) default '',
  reviewer_category_rate2 VARCHAR(20) default '',
  reviewer_category_rate3 VARCHAR(20) default '',
  reviewer_category_rate4 VARCHAR(20) default '',
  reviewer_category_rate5 VARCHAR(20) default '',
  reviewer_category_rate6 VARCHAR(20) default '',
  reviewer_category_rate7 VARCHAR(20) default '',
  reviewer_category_rate8 VARCHAR(20) default '',
  reviewer_category_rate9 VARCHAR(20) default '',
  reviewer_category_rate10 VARCHAR(20) default '',
  reviewer_category_linkicon varchar(100) default '',
  PRIMARY KEY  (reviewer_category_id),
  KEY  reviewer_category_name (reviewer_category_name)
  ) TYPE=MyISAM;
CREATE TABLE reviewer_items (
  reviewer_items_id int(10) unsigned NOT NULL auto_increment,
  reviewer_items_name VARCHAR(50) default '',
  reviewer_items_description TEXT,
  reviewer_items_updated int(10) unsigned NOT NULL default '0',
  reviewer_items_catid int(10) unsigned NOT NULL default '0',
  reviewer_items_url VARCHAR(250) default '',
  reviewer_items_order int(10) unsigned NOT NULL default '0',
  reviewer_items_rate tinyint(3) unsigned NOT NULL default '0',
  reviewer_items_rate1 tinyint(3) unsigned NOT NULL default '0',
  reviewer_items_rate2 tinyint(3) unsigned NOT NULL default '0',
  reviewer_items_rate3 tinyint(3) unsigned NOT NULL default '0',
  reviewer_items_rate4 tinyint(3) unsigned NOT NULL default '0',
  reviewer_items_rate5 tinyint(3) unsigned NOT NULL default '0',
  reviewer_items_rate6 tinyint(3) unsigned NOT NULL default '0',
  reviewer_items_rate7 tinyint(3) unsigned NOT NULL default '0',
  reviewer_items_rate8 tinyint(3) unsigned NOT NULL default '0',
  reviewer_items_rate9 tinyint(3) unsigned NOT NULL default '0',
  reviewer_items_rate10 tinyint(3) unsigned NOT NULL default '0',
  reviewer_items_votes int(10) unsigned NOT NULL default '0',
  reviewer_items_picture VARCHAR(100) default NULL,
  reviewer_items_approved tinyint(3) unsigned NOT NULL default '0',
  reviewer_items_posterid int(10) unsigned NOT NULL default '0',
  PRIMARY KEY  (reviewer_items_id),
  KEY  reviewer_items_catid (reviewer_items_catid),
  KEY reviewer_items_name (reviewer_items_name)
  ) TYPE=MyISAM;
CREATE TABLE reviewer_reviewer (
  reviewer_reviewer_id int(10) unsigned NOT NULL auto_increment,
  reviewer_reviewer_postername VARCHAR(100) default '',
  reviewer_reviewer_itemid int(10) unsigned NOT NULL default '0',
  reviewer_reviewer_posted int(10) unsigned NOT NULL default '0',
  reviewer_reviewer_review text,
  reviewer_reviewer_rate1 tinyint(3) unsigned NOT NULL default '0',
  reviewer_reviewer_rate2 tinyint(3) unsigned NOT NULL default '0',
  reviewer_reviewer_rate3 tinyint(3) unsigned NOT NULL default '0',
  reviewer_reviewer_rate4 tinyint(3) unsigned NOT NULL default '0',
  reviewer_reviewer_rate5 tinyint(3) unsigned NOT NULL default '0',
  reviewer_reviewer_rate6 tinyint(3) unsigned NOT NULL default '0',
  reviewer_reviewer_rate7 tinyint(3) unsigned NOT NULL default '0',
  reviewer_reviewer_rate8 tinyint(3) unsigned NOT NULL default '0',
  reviewer_reviewer_rate9 tinyint(3) unsigned NOT NULL default '0',
  reviewer_reviewer_rate10 tinyint(3) unsigned NOT NULL default '0',
  reviewer_reviewer_email VARCHAR(100) default NULL,
  PRIMARY KEY  (reviewer_reviewer_id),
  KEY reviewer_itemid (reviewer_reviewer_itemid)
  ) TYPE=MyISAM;