<?php
define("LIP_OPTIONS_SAVED","Options Saved!");
define("LIP_USER_ID","User ID");
define("LIP_USER_NAME","User Name");
define("LIP_USER_IP","User IP");
define("LIP_BAN_IP","Ban this IP");
define("LIP_USERS","Users");
define("LIP_PAGES","Pages");
define("LIP_BACK","Back");
define("LIP_FORWARD","Forward");
define("LIP_TABLE_TO_USE","Table to use");
define("LIP_CUSTOM_TABLE","Custom");
define("LIP_LIST_USER_USERS","If using 'user' table, list users.");
define("LIP_YES","Yes");
define("LIP_NO","No");
define("LIP_LANG","Language");
define("LIP_SAVE_PREFS","Save Options");
define("LIP_LAST_IP","Last IP");
define("LIP_ASCENDING","Ascending");
define("LIP_DESCENDING","Descending");
define("LIP_SORT_BY","Sort by");
define("LIP_IN","in");
define("LIP_ORDER","order");
define("LIP_SEARCH","Search");
define("LIP_SEARCH_WHAT","Search in what");
define("LIP_UPP","Users per page");
define("LIP_IPU","IPs per user");
define("LIP_CURRENT","current");
define("LIP_CHANGE_DATE","Change date for a<br />user/ip on each visit");
define("LIP_DELETE","Delete");
define("LIP_DATE","Date");
define("LIP_DELETED"," records deleted");
define("LIP_RECORDS","Records");
?>