// English language strings
hs.lang = {
	cssDirection: 'ltr',
	loadingText: 'Loading...',
	loadingTitle: 'Click to abort',
	focusTitle: 'Click to bring in front',
	fullExpandTitle: 'Expand to original size',
	creditsText: 'Powered by <i>Highslide JS</i>',
	creditsTitle: 'Goto Highslide JS Homepage',
	previousText: 'previous',
	nextText: 'next',
	moveText: 'move',
	closeText: 'close',
	closeTitle: 'close (Esc)',
	resizeTitle: 'restore size',
	playText: 'play',
	playTitle: 'play slideshow (SPACE)',
	pauseText: 'pause',
	pauseTitle: 'pause slideshow (SPACE)',
	previousTitle: 'previous (ARROW LEFT)',
	nextTitle: 'next (ARROW RIGHT)',
	moveTitle: 'move',
	fullExpandText: 'fullscreen',
	number: 'image %1 of %2',
	restoreTitle: 'Click to close image, click and drag to move. Use arrow keys to navigate next and back.'
};