<?php
/*
+---------------------------------------------------------------+
|        e107 website system
|        ../../e107_plugins/content/menus/content_ROK jako žádný jiný_menu.php
|
|        (C)Steve Dunstan 2001-2002
|        http://e107.org
|        jalist@e107.org
|
|        Released under the terms and conditions of the
|        GNU General Public License (http://gnu.org).
+---------------------------------------------------------------+

This file has been generated by ../../e107_plugins/content/handlers/content_class.php.

*/


unset($text);
$text = "";
$menutypeid		= "2";
$menuname		= "LÉTO jako žádné jiné";

$plugindir		= e_PLUGIN.'content/';
$plugintable	= "pcontent";		//name of the table used in this plugin (never remove this, as it's being used throughout the plugin !!)
$datequery		= " AND content_datestamp < ".time()." AND (content_enddate=0 || content_enddate>".time().") ";

require_once(e_PLUGIN.'content/handlers/content_class.php');
$aa = new content;
require_once(e_HANDLER.'form_handler.php');
$rs = new form;
$gen = new convert;
global $tp;

include_lan(e_PLUGIN.'content/languages/'.e_LANGUAGE.'/lan_content.php');

					$bullet = '';
					if(defined('BULLET'))
					{
						$bullet = '<img src="'.THEME.'images/'.BULLET.'" alt="" style="vertical-align: middle;" />';
					}
					elseif(file_exists(THEME.'images/bullet2.gif'))
					{
						$bullet = '<img src="'.THEME.'images/bullet.png" alt="" style="vertical-align: middle;" />';
					}
			$content_pref					= $aa -> getContentPref($menutypeid);
$content_icon_path				= $tp -> replaceConstants($content_pref["content_icon_path"]);
$content_cat_icon_path_small	= $tp -> replaceConstants($content_pref["content_cat_icon_path_small"]);

	$break = FALSE;
//##### SEARCH SELECT ORDER --------------------------------------------------
 
$sql -> db_Select($plugintable, "content_heading", "content_id='".$menutypeid."' ");
$row = $sql -> db_Fetch();
$caption =  $row['content_heading'];
  

//get category array
$array = $aa -> getCategoryTree("", intval($menutypeid), TRUE);

//##### CATEGORY LIST --------------------------------------------------
if(!$content_pref["content_menu_cat_dropdown"]){
	if($content_pref["content_menu_cat"]){
				$text .= "<ul class='list-group'>"; 

		$newparent = "";
		$checkid = "";
		$newarray = array_merge_recursive($array);
		for($a=0;$a<count($newarray);$a++){
			for($b=0;$b<count($newarray[$a]);$b++){
				$newparent[$newarray[$a][$b]] = $newarray[$a][$b+1];
				if( $newarray[$a][$b] != $menutypeid ){
					$checkid .= " content_id = '".$newarray[$a][$b]."' OR ";
				}
         
				$b++;
			}
		}
		$checkid = substr($checkid,0,-3);
		if(!is_object($sql)){ $sql = new db; }
		if($sql -> db_Select($plugintable, "*", " ".$checkid." ORDER BY SUBSTRING_INDEX(content_order, '.', 1)+0 ")){
			while($row = $sql -> db_Fetch()){
 
				//display category list
;
 
				$text .= "<li class='list-group-item'><div>";
	//			$text .= "<a href='".e_PLUGIN_ABS."content/content.php?cat.".$row['content_id']."'>".$row['content_heading']."</a>";
  
				$row['content_sef'] = eHelper::title2sef($row['content_heading'],'dashl');
        $row['content_query'] = "?cat.".$row['content_id'];
        $url = e107::url("content", "content", $row, "full");        
        
				$text .= "<a href='".$url."'>".$row['content_heading']."</a>";
        
				$text .= ($content_pref["content_menu_cat_number"] ? " <span class='smalltext'>(".$aa -> countCatItems($row['content_id']).")</span>" : "");
				$text .= "</div></li>";
 
 
			}
		}
  	 $text .= "</ul>";
	}
}

 
 
if(!isset($text)){ $text = CONTENT_MENU_LAN_1; }

$ns -> tablerender($caption, $text, ' ');

?>