<?php
/*
+---------------------------------------------------------------+
|        e107 website system
|        ../../aylno_plugins/content/menus/content_Doprovodné povídky_menu.php
|
|        (C)Steve Dunstan 2001-2002
|        http://e107.org
|        jalist@e107.org
|
|        Released under the terms and conditions of the
|        GNU General Public License (http://gnu.org).
+---------------------------------------------------------------+

This file has been generated by ../../aylno_plugins/content/handlers/content_class.php.

*/


unset($text);
$text = "";
$menutypeid		= "53";
$menuname		= "Doprovodné povídky";

$plugindir		= e_PLUGIN.'content/';
$plugintable	= "pcontent";		//name of the table used in this plugin (never remove this, as it's being used throughout the plugin !!)
$datequery		= " AND content_datestamp < ".time()." AND (content_enddate=0 || content_enddate>".time().") ";

require_once(e_PLUGIN.'content/handlers/content_class.php');
$aa = new content;
require_once(e_HANDLER.'form_handler.php');
$rs = new form;
$gen = new convert;
global $tp;

include_lan(e_PLUGIN.'content/languages/'.e_LANGUAGE.'/lan_content.php');

					$bullet = '';
					if(defined('BULLET'))
					{
						$bullet = '<img src="'.THEME.'images/'.BULLET.'" alt="" style="vertical-align: middle;" />';
					}
					elseif(file_exists(THEME.'images/bullet2.gif'))
					{
						$bullet = '<img src="'.THEME.'images/bullet2.gif" alt="" style="vertical-align: middle;" />';
					}
			$content_pref					= $aa -> getContentPref($menutypeid);
$content_icon_path				= $tp -> replaceConstants($content_pref["content_icon_path"]);
$content_cat_icon_path_small	= $tp -> replaceConstants($content_pref["content_cat_icon_path_small"]);

	$break = FALSE;
//##### SEARCH SELECT ORDER --------------------------------------------------
//show search box
if($content_pref["content_menu_search"]){
	$text .= $aa -> showOptionsSearch("menu", $menutypeid);
	$break = TRUE;
}
//show select box (with either links to other content pages, to categories, to both, or don't show at all)
if( ($content_pref["content_menu_links"] && $content_pref["content_menu_links_dropdown"]) || ($content_pref["content_menu_cat"] && $content_pref["content_menu_cat_dropdown"]) ){
	$text .= $aa -> showOptionsSelect("menu", $menutypeid);
	$break = TRUE;
}
//show order box
if($content_pref["content_menu_sort"]){
	$text .= $aa -> showOptionsOrder("menu", $menutypeid);
	$break = TRUE;
}

//show links list if chosen so
if($content_pref["content_menu_links"] && !$content_pref["content_menu_links_dropdown"]){
	if($break === TRUE){
	   $text .= "<br />";
	}
	$text .= ($content_pref["content_menu_links_caption"] != "" ? $content_pref["content_menu_links_caption"] : CONTENT_MENU_LAN_4)."<br />";

	//define icon
	if($content_pref["content_menu_links_icon"] == "0"){ $linksicon = "";
	}elseif($content_pref["content_menu_links_icon"] == "1"){ $linksicon = $bullet;
	}elseif($content_pref["content_menu_links_icon"] == "2"){ $linksicon = "&middot";
	}elseif($content_pref["content_menu_links_icon"] == "3"){ $linksicon = "&ordm;";
	}elseif($content_pref["content_menu_links_icon"] == "4"){ $linksicon = "&raquo;";
	}

	if($content_pref["content_menu_viewallcat"]){
		$text .= $linksicon." <a href='".$plugindir."content.php?cat.list.".$menutypeid."'>".CONTENT_LAN_6."</a><br />";
	}
	if($content_pref["content_menu_viewallauthor"]){
		$text .= $linksicon." <a href='".$plugindir."content.php?author.list.".$menutypeid."'>".CONTENT_LAN_7."</a><br />";
	}
	if($content_pref["content_menu_viewallitems"]){
		$text .= $linksicon." <a href='".$plugindir."content.php?list.".$menutypeid."'>".CONTENT_LAN_83."</a><br />";
	}
	if($content_pref["content_menu_viewtoprated"]){
		$text .= $linksicon." <a href='".$plugindir."content.php?top.".$menutypeid."'>".CONTENT_LAN_8."</a><br />";
	}
	if($content_pref["content_menu_viewtopscore"]){
		$text .= $linksicon." <a href='".$plugindir."content.php?score.".$menutypeid."'>".CONTENT_LAN_12."</a><br />";
	}
	if($content_pref["content_menu_viewrecent"]){
		$text .= $linksicon." <a href='".$plugindir."content.php?recent.".$menutypeid."'>".CONTENT_LAN_61."</a><br />";
	}
	if( $content_pref["content_menu_viewsubmit"] && $content_pref["content_submit"] && check_class($content_pref["content_submit_class"]) ){
		$text .= $linksicon." <a href='".$plugindir."content_submit.php'>".CONTENT_LAN_75."</a><br />";
	}
	$text .= "<br />";
}

//get category array
$array = $aa -> getCategoryTree("", intval($menutypeid), TRUE);

//##### CATEGORY LIST --------------------------------------------------
if(!$content_pref["content_menu_cat_dropdown"]){
	if($content_pref["content_menu_cat"]){
		$text .= ($content_pref["content_menu_cat_caption"] != "" ? $content_pref["content_menu_cat_caption"] : CONTENT_MENU_LAN_3)."<br />";

		$newparent = "";
		$checkid = "";
		$newarray = array_merge_recursive($array);
		for($a=0;$a<count($newarray);$a++){
			for($b=0;$b<count($newarray[$a]);$b++){
				$newparent[$newarray[$a][$b]] = $newarray[$a][$b+1];
				if( ($content_pref["content_menu_cat_main"] && $newarray[$a][$b] == $menutypeid) || $newarray[$a][$b] != $menutypeid ){
					$checkid .= " content_id = '".$newarray[$a][$b]."' OR ";
				}
				$b++;
			}
		}
		$checkid = substr($checkid,0,-3);
		if(!is_object($sql)){ $sql = new db; }
		if($sql -> db_Select($plugintable, "*", " ".$checkid." ORDER BY SUBSTRING_INDEX(content_order, '.', 1)+0 ")){
			while($row = $sql -> db_Fetch()){

				//define icon
				$ICON = "";
				if($content_pref["content_menu_cat_icon"] == "0"){ $ICON = "";
				}elseif($content_pref["content_menu_cat_icon"] == "1"){ $ICON = $bullet;
				}elseif($content_pref["content_menu_cat_icon"] == "2"){ $ICON = "&middot";
				}elseif($content_pref["content_menu_cat_icon"] == "3"){ $ICON = "&ordm;";
				}elseif($content_pref["content_menu_cat_icon"] == "4"){ $ICON = "&raquo;";
				}elseif($content_pref["content_menu_cat_icon"] == "5"){
					if($row['content_icon'] != "" && file_exists($content_cat_icon_path_small.$row['content_icon']) ){
						$ICON = "<img src='".$content_cat_icon_path_small.$row['content_icon']."' alt='' style='border:0;' />";
					}else{
						//default category icon
						if($content_pref["content_menu_cat_icon_default"] == "0"){ $ICON = "";
						}elseif($content_pref["content_menu_cat_icon_default"] == "1"){ $ICON = $bullet;
						}elseif($content_pref["content_menu_cat_icon_default"] == "2"){ $ICON = "&middot";
						}elseif($content_pref["content_menu_cat_icon_default"] == "3"){ $ICON = "&ordm;";
						}elseif($content_pref["content_menu_cat_icon_default"] == "4"){ $ICON = "&raquo;";
						}
					}
				}
				//display category list
				$text .= "<table style='width:100%; text-align:left; border:0;' cellpadding='0' cellspacing='0'>";
				$text .= "<tr>";
				$text .= ($ICON ? "<td style='width:1%; white-space:nowrap; text-align:left; padding-right:5px;'><a href='".e_PLUGIN."content/content.php?cat.".$row['content_id']."'>".$ICON."</a></td>" : "");
				$text .= "<td colspan='2'>";
				$text .= "<a href='".e_PLUGIN."content/content.php?cat.".$row['content_id']."'>".$row['content_heading']."</a>";
				$text .= ($content_pref["content_menu_cat_number"] ? " <span class='smalltext'>(".$aa -> countCatItems($row['content_id']).")</span>" : "");
				$text .= "</td>";
				$text .= "</tr>";
				$text .= "</table>";
			}
		}
	}
}

//##### RECENT --------------------------------------------------
if($content_pref["content_menu_recent"]){
	$text .= "<br />";

	//prepare query paramaters
	$validparent = implode(",", array_keys($array));
	$qry = " content_parent REGEXP '".$aa -> CONTENTREGEXP($validparent)."' ";

	$sql1 = new db;
	$contenttotal = $sql1 -> db_Count($plugintable, "(*)", "WHERE content_refer != 'sa' AND ".$qry." ".$datequery." AND content_class REGEXP '".e_CLASS_REGEXP."' " );

	if($resultitem = $sql1 -> db_Select($plugintable, "*", "content_refer !='sa' AND ".$qry." ".$datequery." AND content_class REGEXP '".e_CLASS_REGEXP."' ORDER BY content_datestamp DESC LIMIT 0,".$content_pref["content_menu_recent_number"] )){

		$text .= ($content_pref["content_menu_recent_caption"] != "" ? $content_pref["content_menu_recent_caption"] : CONTENT_MENU_LAN_2)."<br />";
		while($row = $sql1 -> db_Fetch()){

			$ICON = "";
			$DATE = "";
			$AUTHOR = "";
			$SUBHEADING = "";

			if($content_pref["content_menu_recent_date"]){
				$datestyle = ($content_pref["content_archive_datestyle"] ? $content_pref["content_archive_datestyle"] : "%d %b %Y");
				$DATE = strftime($datestyle, $row['content_datestamp']);
			}
			if($content_pref["content_menu_recent_author"]){
				$authordetails = $aa -> getAuthor($row['content_author']);
				$AUTHOR = $authordetails[1];
			}

			//subheading
			if($content_pref["content_menu_recent_subheading"] && $row['content_subheading']){
				if($content_pref["content_menu_recent_subheading_char"] && $content_pref["content_menu_recent_subheading_char"] != "" && $content_pref["content_menu_recent_subheading_char"] != "0"){
					if(strlen($row['content_subheading']) > $content_pref["content_menu_recent_subheading_char"]) {
						$row['content_subheading'] = substr($row['content_subheading'], 0, $content_pref["content_menu_recent_subheading_char"]).$content_pref["content_menu_recent_subheading_post"];
					}
				}
				$SUBHEADING = $row['content_subheading'];
			}

			//define icon
			$recenticonwidth = "";
			if($content_pref["content_menu_recent_icon"] == "0"){ $ICON = "";
			}elseif($content_pref["content_menu_recent_icon"] == "1"){ $ICON = $bullet;
			}elseif($content_pref["content_menu_recent_icon"] == "2"){ $ICON = "&middot";
			}elseif($content_pref["content_menu_recent_icon"] == "3"){ $ICON = "&ordm;";
			}elseif($content_pref["content_menu_recent_icon"] == "4"){ $ICON = "&raquo;";
			}elseif($content_pref["content_menu_recent_icon"] == "5"){
				if($content_pref["content_menu_recent_icon"] == "5"){
					if($content_pref["content_menu_recent_icon_width"]){
						$recenticonwidth = " width:".$content_pref["content_menu_recent_icon_width"]."px; ";
					}else{
						$recenticonwidth = " width:50px; ";
					}
				}
				if($content_pref["content_menu_recent_icon"] == "5" && $row['content_icon'] != "" && file_exists($content_icon_path.$row['content_icon'])){
					$ICON = "<img src='".$content_icon_path.$row['content_icon']."' alt='' style='".$recenticonwidth." border:0;' />";
				}
			}

			//display recent list
			$text .= "<table style='width:100%; text-align:left; border:0; margin-bottom:10px;' cellpadding='0' cellspacing='0'>";
			$text .= "<tr>";
			$text .= ($ICON ? "<td style='width:1%; white-space:nowrap; vertical-align:top; padding-right:5px;'><a href='".e_PLUGIN."content/content.php?content.".$row['content_id']."'>".$ICON."</a></td>" : "");
			$text .= "<td style='width:99%; vertical-align:top;'>";
			$text .= "<a href='".e_PLUGIN."content/content.php?content.".$row['content_id']."'>".$row['content_heading']."</a><br />";
			$text .= ($DATE ? $DATE."<br />" : "" );
			$text .= ($AUTHOR ? $AUTHOR."<br />" : "" );
			$text .= ($SUBHEADING ? $SUBHEADING."<br />" : "" );
			$text .= "</td>";
			$text .= "</tr>";
			$text .= "</table>";
		}
	}
}

if(!isset($text)){ $text = CONTENT_MENU_LAN_1; }
$caption = ($content_pref["content_menu_caption"] != "" ? $content_pref["content_menu_caption"] : CONTENT_MENU_LAN_0." ".$menuname);
$ns -> tablerender($caption, $text, 'content_Doprovodné povídky');

?>