<?php
/*
+---------------------------------------------------------------+
|        e107 website system
|        ../../e107_plugins/content/menus/content_ROK jako žádný jiný_menu.php
|
|        (C)Steve Dunstan 2001-2002
|        http://e107.org
|        jalist@e107.org
|
|        Released under the terms and conditions of the
|        GNU General Public License (http://gnu.org).
+---------------------------------------------------------------+

This file has been generated by ../../e107_plugins/content/handlers/content_class.php.

*/


unset($text);
$text = "";
$menutypeid		= "0";
$menuname		= "Novinky";

$plugindir		= e_PLUGIN.'content/';
$plugintable	= "pcontent";		//name of the table used in this plugin (never remove this, as it's being used throughout the plugin !!)
$datequery		= " AND content_datestamp < ".time()." AND (content_enddate=0 || content_enddate>".time().") ";

require_once(e_PLUGIN.'content/handlers/content_class.php');
$aa = new content;
require_once(e_HANDLER.'form_handler.php');
$rs = new form;
$gen = new convert;
global $tp;

include_lan(e_PLUGIN.'content/languages/'.e_LANGUAGE.'/lan_content.php');

					$bullet = '';
 
$content_pref				    	= $aa -> getContentPref($menutypeid);
$content_icon_path				= $tp -> replaceConstants($content_pref["content_icon_path"]);
$content_cat_icon_path_small	= $tp -> replaceConstants($content_pref["content_cat_icon_path_small"]);

	$break = FALSE;
//##### SEARCH SELECT ORDER --------------------------------------------------
 

 

//get category array
$array = $aa -> getCategoryTree("", intval($menutypeid), TRUE);

 
$text = "<ul>";
//##### RECENT --------------------------------------------------
if($content_pref["content_menu_recent"]){
 

	//prepare query paramaters
	$validparent = implode(",", array_keys($array));
	$qry = " content_parent REGEXP '".$aa -> CONTENTREGEXP($validparent)."' ";
 
	$sql1 = new db;
	$contenttotal = $sql1 -> db_Count($plugintable, "(*)", "WHERE content_refer != 'sa' AND ".$qry." ".$datequery." AND content_class REGEXP '".e_CLASS_REGEXP."' " );

	if($resultitem = $sql1 -> db_Select($plugintable, "*", "content_refer !='sa' AND ".$qry." ".$datequery." AND content_class REGEXP '".e_CLASS_REGEXP."' ORDER BY content_datestamp DESC LIMIT 0,".$content_pref["content_menu_recent_number"] )){

 
		while($row = $sql1 -> db_Fetch()){

			$ICON = "";
			$DATE = "";
			$AUTHOR = "";
			$SUBHEADING = "";

 
				$datestyle =  "%d %b %Y";
				$DATE = strftime($datestyle, $row['content_datestamp']);
		 
 
				$authordetails = $aa -> getAuthor($row['content_author']);
				$AUTHOR = $authordetails[1];
		 

			//subheading
 
				$SUBHEADING = $row['content_subheading'];
	 

			//define icon
			$recenticonwidth = "";
			if($content_pref["content_menu_recent_icon"] == "0"){ $ICON = "";
			}elseif($content_pref["content_menu_recent_icon"] == "1"){ $ICON = $bullet;
			}elseif($content_pref["content_menu_recent_icon"] == "2"){ $ICON = "&middot";
			}elseif($content_pref["content_menu_recent_icon"] == "3"){ $ICON = "&ordm;";
			}elseif($content_pref["content_menu_recent_icon"] == "4"){ $ICON = "&raquo;";
			}elseif($content_pref["content_menu_recent_icon"] == "5"){
				if($content_pref["content_menu_recent_icon"] == "5"){
					if($content_pref["content_menu_recent_icon_width"]){
						$recenticonwidth = " width:".$content_pref["content_menu_recent_icon_width"]."px; ";
					}else{
						$recenticonwidth = " width:50px; ";
					}
				}
				if($content_pref["content_menu_recent_icon"] == "5" && $row['content_icon'] != "" && file_exists($content_icon_path.$row['content_icon'])){
					$ICON = "<img src='".$content_icon_path.$row['content_icon']."' alt='' style='".$recenticonwidth." border:0;' />";
				}
			}

			//display recent list
				$row['content_sef'] = eHelper::title2sef($row['content_heading'],'dashl');
        $row['content_query'] = "?cat.".$row['content_id'];
        $url = e107::url("content", "content", $row, "full");    
			$text .= "<li>";
			$text .= ($ICON ? "<div><a href='".$url."'>".$ICON."</a></div>" : "");
			$text .= "<div>";
     
        
				$text .= "<a href='".$url."'>".$row['content_heading']."</a>";
			//$text .= "<a href='".e_PLUGIN."content/content.php?content.".$row['content_id']."'>".$row['content_heading']."</a></div>";
      	$text .= "<div><em>";
      $text .= ($SUBHEADING ? $SUBHEADING."</em></div><div>" : "");
			$text .= ($DATE ? "[".$DATE."]</div><div>" : "" );
			$text .= ($AUTHOR ? $AUTHOR."</div><div>" : "" );

			$text .= "</div>";
			$text .= "</li><br />";
		 
		}
	}
}
$text .= "</ul>";
if(!isset($text)){ $text = CONTENT_MENU_LAN_1; }
$caption =  CONTENT_MENU_LAN_2 ;
$ns -> tablerender($caption, $text, 'content_ROK jako žádný jiný');

?>