#!/usr/bin/perl -w
# Perl script to make a directory as specified on the command line.
# Usage:
# http://url-to-cgi-folder/mkdir?dir=/path/to/be/created&mode=0mmm
#
#   (?dir=xyz) is an absolute path on your fileserver
#   (&mode=0mmm) is octal mode for creating the directory
#
# In Coppermine, this script is configured via two parameters:
#   "SAFE_MODE: URI for mkdir cgi" should be set to the URL, e.g.
#     http://www.mydomain.com/cgi-bin/mkdir
#
#   "SAFE_MODE: Host coppermine path" should be set to the host's
#   internal path to coppermine. On an Apache server, look at
#   SCRIPT_FILENAME. You may find something like:
#    /var/www/html/vhosts/mydomain/coppermine/
#
# This script can be opened as a URL, or fopened directly from php
#
use strict;
use CGI qw/:standard/;

print header();
print start_html(" ");
my $dir = param("dir");
my $mode = param("mode") || 0755;
if (! -d $dir) {
    umask 0000;
    my $ret = mkdir ($dir);
    chmod(oct($mode), $dir);
}
print end_html;

exit 0;
