CREATE TABLE portfolio_cat (
  portfoliocat_id int(10) unsigned NOT NULL auto_increment,
  portfoliocat_name varchar(30) default NULL,
  portfoliocat_description text,
  portfoliocat_created int(10) unsigned NOT NULL default '0',
  portfoliocat_updated int(10) unsigned NOT NULL default '0',
  portfoliocat_order int(10) unsigned NOT NULL default '0',
  portfoliocat_parent int(10) unsigned NOT NULL default '0',
  PRIMARY KEY  (portfoliocat_id)
) TYPE=MyISAM;
CREATE TABLE portfolio_person (
  portfolio_person_id int(10) unsigned NOT NULL auto_increment,
  portfolio_person_name varchar(50) default NULL,
  portfolio_person_poster varchar(100) default NULL,
  portfolio_person_contact text,
  portfolio_person_phone varchar(20) default NULL,
  portfolio_person_email varchar(100) default NULL,
  portfolio_person_websiteurl varchar(250) default NULL,
  portfolio_person_websitename varchar(100) default NULL,
  portfolio_person_affiliate1 varchar(100) default NULL,
  portfolio_person_affiliateurl1 varchar(250) default NULL,
  portfolio_person_affiliate2 varchar(100) default NULL,
  portfolio_person_affiliateurl2 varchar(250) default NULL,
  portfolio_person_affiliate3 varchar(100) default NULL,
  portfolio_person_affiliateurl3 varchar(250) default NULL,
  portfolio_person_biography text,
  portfolio_person_additional text,
  portfolio_person_comments text,
  portfolio_person_portrait1 varchar(100) default NULL,
  portfolio_person_portraittext1 varchar(100) default NULL,
  portfolio_person_portrait2 varchar(100) default NULL,
  portfolio_person_portraittext2 varchar(100) default NULL,
  portfolio_person_portrait3 varchar(100) default NULL,
  portfolio_person_portraittext3 varchar(100) default NULL,
  portfolio_person_gallery1 varchar(100) default NULL,
  portfolio_person_gallerytext1 varchar(100) default NULL,
  portfolio_person_gallery2 varchar(100) default NULL,
  portfolio_person_gallerytext2 varchar(100) default NULL,
  portfolio_person_gallery3 varchar(100) default NULL,
  portfolio_person_gallerytext3 varchar(100) default NULL,
  portfolio_person_gallery4 varchar(100) default NULL,
  portfolio_person_gallerytext4 varchar(100) default NULL,
  portfolio_person_gallery5 varchar(100) default NULL,
  portfolio_person_gallerytext5 varchar(100) default NULL,
  portfolio_person_gallery6 varchar(100) default NULL,
  portfolio_person_gallerytext6 varchar(100) default NULL,
  portfolio_person_videolink varchar(100) default NULL,
  portfolio_person_videolinktext varchar(100) default NULL,
  portfolio_person_attachment varchar(100) default NULL,
  portfolio_person_cat text,
  portfolio_person_created int(10) unsigned NOT NULL default '0',
  portfolio_person_updated int(10) unsigned NOT NULL default '0',
  portfolio_person_order int(10) unsigned NOT NULL default '0',
  portfolio_person_show int(10) unsigned NOT NULL default '0',
  portfolio_person_showemail tinyint(3) unsigned NOT NULL default '0',
  portfolio_person_showphone tinyint(3) unsigned NOT NULL default '0',
  portfolio_person_views int(10) unsigned NOT NULL default '0',
  portfolio_person_unique int(10) unsigned NOT NULL default '0',
  portfolio_person_uniquelist text,
  PRIMARY KEY  (portfolio_person_id)
) TYPE=MyISAM;
